# Generated by Django 5.1.4 on 2024-12-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexaoNormalSimplesRetangularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fck', models.IntegerField(choices=[(20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90)], default=25)),
                ('fyk', models.IntegerField(choices=[(250, 250), (500, 500), (600, 600)], default=500)),
                ('es', models.IntegerField(choices=[(190, 190), (200, 200), (215, 215)], default=200)),
                ('gamac', models.FloatField(default=1.4)),
                ('gamas', models.FloatField(default=1.15)),
                ('gamaf', models.FloatField(default=1.4)),
                ('bduct', models.FloatField(default=1.0)),
                ('b', models.FloatField(default=15)),
                ('h', models.FloatField(default=40)),
                ('d', models.FloatField(default=36)),
                ('amk', models.FloatField(default=30)),
            ],
        ),
    ]
